import './styles/tailwind/theme.css'

import {
  Button,
  type ButtonProps,
  Separator,
  type SeparatorProps,
  Input,
  type InputProps,
  Skeleton,
  type SkeletonProps,
  Spoiler,
  type SpoilerProps,
  Select,
  SelectContent,
  SelectGroup,
  SelectLabel,
  SelectItem,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  Textarea,
  type TextareaProps,
  StackLoader,
  type StackLoaderProps,
  BounceLoader,
  type BounceLoaderProps,
  WasherLoader,
  type WasherLoaderProps,
  MacbookAnimation,
  type MacBookAnimationProps,
  Loader,
  LoaderProps,
} from './components'

export {
  Button,
  type ButtonProps,
  Separator,
  type SeparatorProps,
  Input,
  type InputProps,
  Skeleton,
  type SkeletonProps,
  Spoiler,
  type SpoilerProps,
  Select,
  SelectContent,
  SelectGroup,
  SelectLabel,
  SelectItem,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  Textarea,
  type TextareaProps,
  StackLoader,
  type StackLoaderProps,
  BounceLoader,
  type BounceLoaderProps,
  WasherLoader,
  type WasherLoaderProps,
  MacbookAnimation,
  type MacBookAnimationProps,
  Loader,
  type LoaderProps,
}

import { useScreenSize, useFetch, useLocation } from './hooks'

export { useScreenSize, useFetch, useLocation }
