name: BUILD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .nvmrc
      
      - name: Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      
      - name: Build Package
        run: yarn build
      
      - name: Check Diff
        run: git diff && git diff-index --quiet --exit-code HEAD